# -*- coding: utf-8 -*-
"""tamilocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r13R7RLZN3Gi7frx71n5CJQi4l6lfbnW
"""


import PIL
from PIL import ImageDraw
im = PIL.Image.open("tamilimg.jpeg")
im

import easyocr
reader = easyocr.Reader(['ta','en'])

bounds = reader.readtext('tamilimg.jpeg')
bounds

def draw_boxes(image, bounds, color ='yellow', width=2):
  draw = ImageDraw.Draw(image)
  for bound in bounds:
    p0, p1, p2, p3 = bound[0]
    draw.line([*p0,*p1,*p2,*p3,*p0], fill = color, width=width)
  return image

draw_boxes(im, bounds)

for x in bounds:
  print(x[1].strip())